name: Run Makefile Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-makefile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Make
      run: sudo apt-get install make

    - name: Run say-hello command
      run: make say-hello
